# Generated by Django 4.1.3 on 2022-12-03 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=20)),
                ('codigo_produto', models.CharField(max_length=30)),
                ('quantidade', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_minimo', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['nome_produto'],
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('itens', models.ManyToManyField(to='cadastro_clientes.itens')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=50)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_clientes.conta')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
