# Generated by Django 4.1.3 on 2022-12-03 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='conta',
        ),
        migrations.AddField(
            model_name='conta',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro_clientes.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conta',
            name='quantidade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='conta',
            name='itens',
        ),
        migrations.AddField(
            model_name='conta',
            name='itens',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro_clientes.itens'),
            preserve_default=False,
        ),
    ]
