# Generated by Django 4.1.3 on 2022-12-03 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_produtos', '0001_initial'),
        ('cadastro_clientes', '0003_rename_itens_conta_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro_produtos.itens'),
        ),
        migrations.DeleteModel(
            name='Itens',
        ),
    ]
